export const PROFILE_EXAMPLES = {
  healthConditions: [
    'Hypertension',
    'Diabete type 2',
    'Cholesterol eleve',
    'Reflux gastrique',
    'Arthrose',
    'Anemie',
  ],
  allergies: [
    'Gluten',
    'Lactose',
    'Arachides',
    'Fruits de mer',
    'Oeufs',
    'Soja',
  ],
  dietaryPreferences: [
    'Vegetarien',
    'Peu de viande rouge',
    'Sans porc',
    'Produits locaux et de saison',
    'Batch cooking le dimanche',
    'Peu de sucre ajoute',
  ],
  goals: [
    "Plus d'énergie",
    'Perdre du poids',
    'Renforcement musculaire',
    'Ameliorer le sommeil',
    'Reduire le stress',
    'Mieux recuperer apres effort',
  ],
  breakfast: [
    'Tartines',
    'Cereales',
    'Yaourt',
    'Fruits',
    'Oeufs',
    'Smoothie',
    'Rien / tres leger',
  ],
  lunch: [
    'Salades',
    'Soupes',
    'Plat unique',
    'Sandwich',
    'Batch cooking',
    'Rien / tres leger',
  ],
  dinner: [
    'Salades',
    'Soupes',
    'Poisson',
    'Viande legere',
    'Vegetarien',
    'Plat mijote',
    'Rien / tres leger',
  ],
} as const
